[tool.pyflow]
name = "sammen"
py_version = "3.9"
version = "2022.6.20"
authors = ["Stefan Hagen <stefan@hagen.link>"]

[tool.pyflow.scripts]

[tool.pyflow.dependencies]

[tool.pyflow.dev-dependencies]
